{% set name = "plotille" %}
{% set version = "5.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/plotille-{{ version }}.tar.gz
  sha256: 99e5ca51a2e4c922ead3a3b0863cc2c6a9a4b3f701944589df10f42ce02ab3dc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.7.0,<4.0.0

test:
  imports:
    - plotille
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tammoippen/plotille
  summary: Plot in the terminal using braille dots.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - Satarupa22-SD
